function severityForIndex(index) {
  if (index === 0) return "medium";
  if (index === 1) return "high";
  return "low";
}

async function detectDefectsForRoom(room = {}) {
  const photos = room.photos || [];

  if (!photos.length) {
    return [];
  }

  return photos.slice(0, 3).map((photo, index) => ({
    type: ["crack", "damp", "finish"][index] || "other",
    title: `${room.name || "Room"} finding ${index + 1}`,
    description:
      index === 0
        ? "Surface crack detected near wall edge."
        : index === 1
        ? "Moisture-related staining detected."
        : "Finish quality inconsistency detected.",
    severity: severityForIndex(index),
    confidence: Number((0.7 - index * 0.08).toFixed(2)),
    notes: "Generated by the v1 stub detector. Review before publishing.",
    manualOverride: false,
    annotations: [],
    images: [photo],
  }));
}

function summarizeInspection(inspection) {
  const defects = inspection.defects || [];
  const summary = {
    totalDefects: defects.length,
    lowCount: 0,
    mediumCount: 0,
    highCount: 0,
    criticalCount: 0,
  };

  defects.forEach((defect) => {
    if (defect.severity === "critical") summary.criticalCount += 1;
    if (defect.severity === "high") summary.highCount += 1;
    if (defect.severity === "medium") summary.mediumCount += 1;
    if (defect.severity === "low") summary.lowCount += 1;
  });

  return summary;
}

module.exports = {
  detectDefectsForRoom,
  summarizeInspection,
};

