const DEFAULT_BRAND_COLOR = [0.06, 0.42, 0.56];

const toPlainText = (value) =>
  String(value ?? "")
    .replace(/[^\x20-\x7E]/g, "?")
    .replace(/\s+/g, " ")
    .trim();

const escapePdfText = (value) => toPlainText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const formatDate = (value) => (value ? new Date(value).toISOString() : "TBC");

const formatMoney = (money) => {
  if (money?.amount === null || money?.amount === undefined) {
    return "TBC";
  }

  const amount = new Intl.NumberFormat("en-GB", {
    maximumFractionDigits: 0
  }).format(money.amount);

  return `${money.currency || "GBP"} ${amount}`;
};

const formatPercent = (value) => (value === null || value === undefined ? "TBC" : `${value}%`);

const formatAddress = (property) =>
  [
    property.address?.line1,
    property.address?.line2,
    property.address?.city,
    property.address?.county,
    property.address?.postcode,
    property.address?.country
  ]
    .filter(Boolean)
    .join(", ") || "Untitled property";

const formatCategory = (value) =>
  toPlainText(value || "TBC")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());

const parseBrandColor = (value) => {
  if (!/^#[\da-f]{6}$/i.test(value || "")) {
    return DEFAULT_BRAND_COLOR;
  }

  const red = parseInt(value.slice(1, 3), 16) / 255;
  const green = parseInt(value.slice(3, 5), 16) / 255;
  const blue = parseInt(value.slice(5, 7), 16) / 255;

  return [red, green, blue].map((channel) => Number(channel.toFixed(3)));
};

const buildRiskLines = (risks = []) => {
  if (!risks.length) {
    return ["No risk flags recorded."];
  }

  return risks.slice(0, 8).map((risk) =>
    [risk.severity ? risk.severity.toUpperCase() : "RISK", risk.key, risk.note]
      .filter(Boolean)
      .join(" - ")
  );
};

const buildReportLines = ({ generatedAt, property, user }) => {
  const address = formatAddress(property);
  const companyName = user.companyBranding?.companyName || "AI Realtor";
  const riskLines = buildRiskLines(property.risks || []);

  return [
    { bold: true, size: 21, text: `${companyName} Investor Report` },
    { size: 10, text: `Generated ${formatDate(generatedAt)}` },
    { spacer: 14 },
    { bold: true, size: 15, text: address },
    { text: property.description || "No description captured." },
    { spacer: 10 },
    { bold: true, size: 13, text: "Property Summary" },
    { text: `Listing ID: ${property.source?.listingId || "TBC"}` },
    { text: `Guide price: ${formatMoney(property.prices?.guide)}` },
    { text: `Auction date: ${formatDate(property.auctionDate)}` },
    { text: `Type: ${property.type || "TBC"}` },
    { text: `Tenure: ${property.tenure || "TBC"}` },
    { text: `Bedrooms: ${property.bedrooms ?? "TBC"}` },
    { text: `Floor area: ${property.floorAreaSqFt ? `${property.floorAreaSqFt} sq ft` : "TBC"}` },
    { spacer: 10 },
    { bold: true, size: 13, text: "Deal Scoring" },
    { text: `Deal score: ${property.scoring?.total ?? "TBC"}` },
    { text: `Category: ${formatCategory(property.scoring?.category)}` },
    { text: `Yield score: ${property.scoring?.yieldScore ?? "TBC"}` },
    { text: `Gross yield: ${formatPercent(property.scoring?.grossYield)}` },
    { text: `ROI: ${formatPercent(property.scoring?.roi)}` },
    { text: `ARV: ${formatMoney(property.scoring?.arv)}` },
    { text: `Estimated monthly rent: ${formatMoney({ amount: property.scoring?.rent?.monthly, currency: property.scoring?.rent?.currency })}` },
    { text: `Confidence: ${formatPercent(property.scoring?.confidence)}` },
    { text: `Scoring note: ${property.scoring?.notes || "TBC"}` },
    { spacer: 10 },
    { bold: true, size: 13, text: "Risk Flags" },
    ...riskLines.map((text) => ({ text })),
    { spacer: 10 },
    { bold: true, size: 13, text: "Source" },
    { text: property.source?.url || "No source URL captured." }
  ];
};

const truncateText = (value, maxLength = 96) => {
  const plainText = toPlainText(value);

  return plainText.length > maxLength ? `${plainText.slice(0, maxLength - 3)}...` : plainText;
};

const buildContentStream = ({ brandColor, lines }) => {
  const commands = [
    "q",
    `${brandColor.join(" ")} rg`,
    "0 760 612 32 re f",
    "Q",
    "0.09 0.13 0.16 rg"
  ];
  let y = 724;

  lines.forEach((line) => {
    if (line.spacer) {
      y -= line.spacer;
      return;
    }

    if (y < 58) {
      return;
    }

    const font = line.bold ? "F2" : "F1";
    const size = line.size || 10;
    const text = escapePdfText(truncateText(line.text, line.size && line.size > 14 ? 74 : 100));

    commands.push(`BT /${font} ${size} Tf 50 ${y} Td (${text}) Tj ET`);
    y -= Math.max(size + 6, 15);
  });

  commands.push("0.38 0.44 0.50 rg");
  commands.push(`BT /F1 8 Tf 50 32 Td (${escapePdfText("Generated by AI Realtor")}) Tj ET`);

  return `${commands.join("\n")}\n`;
};

const buildPdf = (contentStream) => {
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${Buffer.byteLength(contentStream, "ascii")} >>\nstream\n${contentStream}endstream`
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "ascii"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "ascii");
  const xrefRows = offsets
    .map((offset, index) => `${String(offset).padStart(10, "0")} ${index === 0 ? "65535" : "00000"} ${index === 0 ? "f" : "n"} `)
    .join("\n");

  pdf += `xref\n0 ${objects.length + 1}\n${xrefRows}\n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "ascii");
};

const generatePropertyReportPdf = async ({ generatedAt = new Date(), property, user }) => {
  const brandColor = parseBrandColor(user.companyBranding?.primaryColor);
  const lines = buildReportLines({ generatedAt, property, user });
  const contentStream = buildContentStream({ brandColor, lines });

  return buildPdf(contentStream);
};

module.exports = {
  generatePropertyReportPdf
};
